# Generated by Django 5.2.8 on 2025-11-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_name', models.CharField(max_length=200)),
                ('latin_name', models.CharField(max_length=200)),
                ('mushroom_type', models.CharField(choices=[('tubular', 'Трубчатые'), ('lamellar', 'Пластинчатые'), ('other', 'Другие')], max_length=20)),
                ('edibility', models.CharField(choices=[('edible', 'Съедобный'), ('conditionally_edible', 'Условно-съедобный'), ('poisonous', 'Ядовитый'), ('deadly', 'Смертельно ядовитый')], max_length=30)),
                ('description', models.TextField()),
                ('habitat', models.TextField()),
                ('season', models.CharField(max_length=100)),
            ],
        ),
    ]
