# Generated by Django 5.2.8 on 2025-11-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='distribution',
            field=models.TextField(blank=True, verbose_name='Распространение'),
        ),
    ]
