# Generated by Django 5.2.8 on 2025-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_mushroom_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mushrooms/'),
        ),
    ]
