# Generated by Django 5.2.8 on 2025-11-25 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0003_mushroom_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название квиза')),
                ('level', models.CharField(choices=[('basic', 'Базовый'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], max_length=20, verbose_name='Уровень сложности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('questions_count', models.PositiveIntegerField(default=20, verbose_name='Количество вопросов')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question_type', models.CharField(choices=[('single', 'Одиночный выбор'), ('multiple', 'Множественный выбор')], default='single', max_length=10, verbose_name='Тип вопроса')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mushrooms.quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=300, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mushrooms.quizquestion')),
            ],
        ),
    ]
