# Generated by Django 5.2.8 on 2025-11-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0004_quiz_quizquestion_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название характеристики')),
                ('question', models.TextField(verbose_name='Вопрос для пользователя')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в определителе')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важная характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='mushroom',
            options={'ordering': ['russian_name'], 'verbose_name': 'Гриб', 'verbose_name_plural': 'Грибы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Квиз', 'verbose_name_plural': 'Квизы'},
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'verbose_name': 'Ответ квиза', 'verbose_name_plural': 'Ответы квиза'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос квиза', 'verbose_name_plural': 'Вопросы квиза'},
        ),
        migrations.AddField(
            model_name='mushroom',
            name='cooking_tips',
            field=models.TextField(blank=True, verbose_name='Советы по приготовлению'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='key_characteristics',
            field=models.TextField(blank=True, verbose_name='Ключевые характеристики'),
        ),
        migrations.AddField(
            model_name='mushroom',
            name='warning',
            field=models.TextField(blank=True, verbose_name='Предупреждение'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='edibility',
            field=models.CharField(choices=[('edible', '🍄 Съедобный'), ('conditionally_edible', '⚠️ Условно-съедобный'), ('poisonous', '☠️ Ядовитый'), ('deadly', '💀 Смертельно ядовитый'), ('inedible', '🚫 Несъедобный')], max_length=30, verbose_name='Съедобность'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='habitat',
            field=models.TextField(verbose_name='Место обитания'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='latin_name',
            field=models.CharField(max_length=200, verbose_name='Латинское название'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='mushroom_type',
            field=models.CharField(choices=[('tubular', 'Трубчатые'), ('lamellar', 'Пластинчатые'), ('other', 'Другие')], max_length=20, verbose_name='Тип гриба'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mushrooms/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='russian_name',
            field=models.CharField(max_length=200, verbose_name='Русское название'),
        ),
        migrations.AlterField(
            model_name='mushroom',
            name='season',
            field=models.CharField(max_length=100, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mushrooms.quizquestion', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mushrooms.quiz', verbose_name='Квиз'),
        ),
        migrations.CreateModel(
            name='CharacteristicOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('description', models.TextField(verbose_name='Описание для пользователя')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushrooms.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Вариант характеристики',
                'verbose_name_plural': 'Варианты характеристик',
                'ordering': ['characteristic__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lookalike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_level', models.CharField(choices=[('low', '🟡 Низкая опасность'), ('medium', '🟠 Средняя опасность'), ('high', '🔴 Высокая опасность'), ('deadly', '💀 Смертельно опасен')], max_length=20, verbose_name='Уровень опасности')),
                ('differences', models.TextField(verbose_name='Ключевые отличия')),
                ('visual_differences', models.TextField(verbose_name='Визуальные отличия')),
                ('warning', models.TextField(blank=True, verbose_name='Особое предупреждение')),
                ('lookalike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appears_as_lookalike', to='mushrooms.mushroom', verbose_name='Гриб-двойник')),
                ('mushroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_mushroom_lookalikes', to='mushrooms.mushroom', verbose_name='Основной гриб')),
            ],
            options={
                'verbose_name': 'Двойник гриба',
                'verbose_name_plural': 'Двойники грибов',
                'unique_together': {('mushroom', 'lookalike')},
            },
        ),
        migrations.CreateModel(
            name='MushroomCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushrooms.characteristic', verbose_name='Характеристика')),
                ('mushroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushrooms.mushroom', verbose_name='Гриб')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushrooms.characteristicoption', verbose_name='Выбранный вариант')),
            ],
            options={
                'verbose_name': 'Характеристика гриба',
                'verbose_name_plural': 'Характеристики грибов',
                'unique_together': {('mushroom', 'characteristic')},
            },
        ),
    ]
