# Generated by Django 5.2.8 on 2025-11-26 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0005_characteristic_alter_mushroom_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('score', models.PositiveIntegerField(verbose_name='Количество баллов')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Правильные ответы')),
                ('wrong_answers', models.PositiveIntegerField(verbose_name='Неправильные ответы')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Всего вопросов')),
                ('percentage', models.PositiveIntegerField(verbose_name='Процент правильных ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mushrooms.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Результат квиза',
                'verbose_name_plural': 'Результаты квизов',
                'ordering': ['-created_at'],
            },
        ),
    ]
